version: "3.9"

services:
  flask_app:
    container_name: flask_app
    image: flask-app
    build: .
    ports:
      - "5000:5000"
    env_file: .env-docker
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:15.3
    ports:
      - "5432:5432"
    env_file: .env-docker
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
